alias ...=../..
alias ....=../../..
alias .....=../../../..
alias ......=../../../../..
alias 1='cd -1'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'
alias 6='cd -6'
alias 7='cd -7'
alias 8='cd -8'
alias 9='cd -9'
alias _='sudo '
alias acti='source ./venv/bin/activate'
alias bsi='brew services info'
alias bsl='brew services list'
alias bsr='brew services restart'
alias chmox=chmod
alias dG=/Users/jadennation/dev/bin/deleteGrandma.py
alias deac=deactivate
alias dg=/Users/jadennation/dev/bin/deleteGrandma.py
alias egrep='grep -E'
alias fgrep='grep -F'
alias findFile='find . -type f -iname'
alias globurl='noglob urlglobber '
alias grep='grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox,.venv,venv}'
alias gs='git status'
alias k=kubectl
alias kc='kubectl config'
alias kk='kubectl krew'
alias kk_i='kubectl krew install tree'
alias kk_s='kubectl krew search'
alias l='ls -lah'
alias la='ls -lAh'
alias ll='ls -lh'
alias ls='ls -G'
alias lsa='ls -lah'
alias md='mkdir -p'
alias mpvStandard='mpv --directory-mode=recursive /Volumes/ext_store/vid /Users/jadennation/Downloads/drive/vid'
alias rd=rmdir
alias rezsh='source "$ZSHRC"'
alias run-help=man
alias ta='tmux -CC attach'
alias tmux='tmux -CC'
alias vim=nvim
alias vimVim='vim ~/.vimrc'
alias vimZ='vim "$ZSHRC"'
alias 'which-command'=whence
alias findDir='find . -type d -iname'
alias vimT="vim ~/.tmux.conf"

